services:
  backend:
    image: s238202/mern-backend:1.0
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: "mongodb+srv://s238202:s238202@cluster0.7h39ffa.mongodb.net/cloud_lab?appName=Cluster0"
      PORT: 5000

  frontend:
    image: s238202/mern-frontend:1.0
    ports:
      - "4173:4173"