services:
  backend:
    build:
      context: ./mern-demo
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: "mongodb+srv://s238202:s238202@cluster0.7h39ffa.mongodb.net/?appName=Cluster0"

  frontend:
    build:
      context: ./mern-demo/client
      dockerfile: Dockerfile
    ports:
      - "4173:4173"